// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn6q5BeWbNbbTpFbXP7ZKSfo8B0Hy4tJw',
    appId: '1:65544552444:web:cca3deba42089263b43c79',
    messagingSenderId: '65544552444',
    projectId: 'infodash-a991c',
    authDomain: 'infodash-a991c.firebaseapp.com',
    storageBucket: 'infodash-a991c.appspot.com',
    measurementId: 'G-TRB4ND8C2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7U1td3fD5fcGaXVPFLBtWf-9_LgnhJ2g',
    appId: '1:65544552444:android:52ac6aea34435d91b43c79',
    messagingSenderId: '65544552444',
    projectId: 'infodash-a991c',
    storageBucket: 'infodash-a991c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYv8uByoz3k-PC0NJMr0qMK_kq5WWKbuo',
    appId: '1:65544552444:ios:1bad128bf05c856eb43c79',
    messagingSenderId: '65544552444',
    projectId: 'infodash-a991c',
    storageBucket: 'infodash-a991c.appspot.com',
    iosClientId: '65544552444-u44sudr51j7ldjbrq0j9rlotf4ed4etl.apps.googleusercontent.com',
    iosBundleId: 'com.example.infodashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYv8uByoz3k-PC0NJMr0qMK_kq5WWKbuo',
    appId: '1:65544552444:ios:1bad128bf05c856eb43c79',
    messagingSenderId: '65544552444',
    projectId: 'infodash-a991c',
    storageBucket: 'infodash-a991c.appspot.com',
    iosClientId: '65544552444-u44sudr51j7ldjbrq0j9rlotf4ed4etl.apps.googleusercontent.com',
    iosBundleId: 'com.example.infodashApp',
  );
}
