// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMJFs7_QflHHi195ShoknlXfga6rRCRIs',
    appId: '1:650264728630:web:baa86963f37d165c077497',
    messagingSenderId: '650264728630',
    projectId: 'infodash-latest',
    authDomain: 'infodash-latest.firebaseapp.com',
    storageBucket: 'infodash-latest.appspot.com',
    measurementId: 'G-B7S9X23MRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrvqifKs_3OzIL4Eh_VUhNxS6Ej91-D2U',
    appId: '1:650264728630:android:125119120ed24bab077497',
    messagingSenderId: '650264728630',
    projectId: 'infodash-latest',
    storageBucket: 'infodash-latest.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtn5RTXU2WKP70stjxXxSNtxRcXWMCh0A',
    appId: '1:650264728630:ios:8dd76d73bd600439077497',
    messagingSenderId: '650264728630',
    projectId: 'infodash-latest',
    storageBucket: 'infodash-latest.appspot.com',
    iosClientId: '650264728630-77d1qhb36iiorn4uuob315c86o37ea3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.infodashApp',
  );
}
